/*
 * Copyright (C) 2026 RavHub Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 */

import { MigrationInterface, QueryRunner } from 'typeorm';

export class Migration1733950300000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Check if default backup storage exists
    const existing = await queryRunner.query(
      `SELECT id FROM "storage_configs" WHERE "usage" = 'backup' AND "isDefault" = true`,
    );

    if (existing.length === 0) {
      // Create default backup storage
      // We use a fixed UUID or generate one. Since we can't easily import uuid here without deps issues sometimes,
      // we'll rely on the database to generate it if possible, or provide a random one.
      // Assuming pgcrypto or uuid-ossp might not be enabled, let's try to insert without ID if it's auto-generated,
      // but the entity definition says @PrimaryGeneratedColumn('uuid').
      // Usually TypeORM migrations generated by CLI use uuid_generate_v4().
      // Let's try to use a hardcoded UUID for this default config to be safe and consistent.

      await queryRunner.query(
        `INSERT INTO "storage_configs" ("id", "key", "type", "config", "isDefault", "usage", "createdAt", "updatedAt")
         VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'backups-local', 'filesystem', '{"basePath": "/data/storage/backups"}', true, 'backup', NOW(), NOW())`,
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM "storage_configs" WHERE "key" = 'backups-local'`,
    );
  }
}
